# Generated by Django 6.0.3 on 2026-03-06 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resume_file', models.FileField(help_text='Original uploaded resume (PDF/DOCX)', upload_to='resumes/original/%Y/%m/')),
                ('resume_text', models.TextField(blank=True, help_text='Extracted raw text from resume (for ATS parsing)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('scored', 'Scored'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted')], default='pending', max_length=20)),
                ('ats_score', models.FloatField(blank=True, help_text='Overall ATS match score (0–100)', null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, help_text='Role overview / company intro')),
                ('experience', models.TextField(blank=True, help_text='Years and type of experience required')),
                ('technical_skills', models.TextField(blank=True, help_text='e.g. Python, Django, React')),
                ('soft_skills', models.TextField(blank=True, help_text='e.g. Communication, Leadership')),
                ('languages', models.TextField(blank=True, help_text='e.g. English (Fluent), Tamil (Native)')),
                ('project_keywords', models.TextField(blank=True, help_text='Keywords to look for in candidate projects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Description',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_score', models.FloatField(blank=True, null=True)),
                ('soft_skills_score', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('language_score', models.FloatField(blank=True, null=True)),
                ('projects_score', models.FloatField(blank=True, null=True)),
                ('matched_skills', models.TextField(blank=True, help_text='Comma-separated matched skills')),
                ('missing_skills', models.TextField(blank=True, help_text='Comma-separated skills not found in resume')),
                ('summary_feedback', models.TextField(blank=True, help_text='Short AI-generated summary of candidate fit', null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_result', to='ats.candidatesubmission')),
            ],
        ),
    ]
